### ISSUE TITLE
Codacy as code quality

### ISSUE THREAD

**Issue by PeterNgTr** [allankp/pytest-testrail#116]
@allankp I would think using the Codacy as code quality to improve our quality would be a nice trying. Also it's totally free and I guess more and more open sources are using it. I'm also using it with my projects, for example: https://www.codacy.com/manual/PeterNgTr/codeceptjs-testrail?utm_source=github.com&utm_medium=referral&utm_content=PeterNgTr/codeceptjs-testrail&utm_campaign=Badge_Grade

**Comment by allankp** [comment]
Had a look at this and it looked pretty interesting. Implemented and tested it out on another repo of mine. Done the same for this one, can tweak it over time. 
Thanks for the suggestion.
