### ISSUE TITLE
Add test parametrize to result

### ISSUE THREAD

**Issue by voloxastik** [allankp/pytest-testrail#133]
I suggest adding a description of the test parameters to the result
PR: https://github.com/allankp/pytest-testrail/pull/132

**Comment by voloxastik** [comment]
Hi, @allankp when is the new version available in PyPI?

**Comment by allankp** [comment]
> Hi, @allankp when is the new version available in PyPI?

How about right now 👍

**Comment by voloxastik** [comment]
thanks a lot
