### ISSUE TITLE
Argument/config handling issues

### ISSUE THREAD

**Issue by brherger** [allankp/pytest-testrail#28]
Using:
Python 2.7.9
pytest-testrail (1.0.1)

Example usage in readme does not appear to work.
`$ pytest test_me.py --testrail=testrail.cfg`
`usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --testrail: ignored explicit argument 'testrail.cfg'`

**Comment by allankp** [comment]
@brherger 
pytest --testrail --tr-config=TR_CONFIG

The config is passed in as a seperate argument.
https://github.com/allankp/pytest-testrail#all-available-options
