### ISSUE TITLE
support configurable `include_all` when creating new test run

### ISSUE THREAD

**Issue by reverbc** [allankp/pytest-testrail#59]
Hi,

Thanks for creating this great plugin.

In our use case, we might have test engineers design and add test case, while other engineers implement test cases. In the report I'd like to see not only the test cases being executed, also how many are not implemented yet. Since this plugin already have `suite_id`, to achieve this is as simple as toggle the flag on https://github.com/allankp/pytest-testrail/blob/master/pytest_testrail/plugin.py#L296

I'd like to suggest to have a new configurable variable in config file and cli option to toggle the `include_all` value, and have `False` as the default value so current behavior can be kept the same.

I can work on this enhancement if you approve this idea.
Thanks :)

**Comment by allankp** [comment]
@reverbc Yeah seems like a good idea, PR is more than welcome
