### ISSUE TITLE
Logic inverted with option "--tr-dont-publish-blocked"

### ISSUE THREAD

**Issue by svart-riddare** [allankp/pytest-testrail#62]
Greetings,

When I do **not** specify this command line option, testrail prints 
> Option "Don't publish blocked testcases" activated

The reason is that the _publish_blocked_ member variable of _PyTestRailPlugin_ is set to the value of the '--tr-dont-publish-blocked' command line option. From the wording and the code, I would expect this variable to bet set to **not** the command line option value.

**Comment by apallier** [comment]
Hi @svart-riddare, you are right, the logic is inverted but it's a bug...
