### ISSUE TITLE
Support adding a description to a created test run

### ISSUE THREAD

**Issue by TytoDan** [allankp/pytest-testrail#79]
It would be useful for us if we could add a description to a published testrun, configured in the testrail.cfg file. This should (hopefully) be quite a quick addition, adding a parameter to 
https://github.com/allankp/pytest-testrail/blob/47bc4bef97a7c801d2ebd064b495499baac56922/pytest_testrail/plugin.py#L296
and appropriate handling for reading the data.

Cheers for the plugin!

**Comment by allankp** [comment]
@TytoDan are you interested in having a go at adding it ? There is a great number of examples of how this is done in the plugin already. Take a look:
https://github.com/allankp/pytest-testrail/blob/master/pytest_testrail/plugin.py#L120
https://github.com/allankp/pytest-testrail/blob/master/pytest_testrail/conftest.py#L15

**Comment by PeterNgTr** [comment]
I think it can be closed cause the PR has been merged.
