### ISSUE TITLE
Use RawConfigParser instead of ConfigParser to support special characters in passwords

### ISSUE THREAD

**Issue by TytoDan** [allankp/pytest-testrail#80]
Hi,

Having some trouble with a testrail password that contains a '%' symbol. Since this is a special character for ConfigParser interpolation the test is failing instantly.

Would it be possible to use RawConfigParser or are the interpolation features required?

Cheers

**Comment by allankp** [comment]
@TytoDan Have you tried escaping the character ?

**Comment by allankp** [comment]
Closing as no reply for extended period of time, feel free to reopen.

**Comment by LesterBurnham** [comment]
I just wanted to comment on this issue, as I ran into the same problem, where a "%" character in the password was causing ptest-testrail to break. The workaround was to add a second "%" character, as described here: https://stackoverflow.com/a/28874886/1798547
