### ISSUE TITLE
Allow test runs to be assigned to a milestone id

### ISSUE THREAD

**Issue by archanaGupta1** [allankp/pytest-testrail#87]
It would be useful to create test runs that can be optionally added to a milestone during creation

**Describe the solution you'd like**
allow a milestone_id to be specified in .cfg file and support command line option for it like other parameters.

I would be happy to submit a PR if the request to change is approved.

**Comment by allankp** [comment]
Go for it @archanaGupta1 :+1:

**Comment by hottes** [comment]
Hi,
This is something we would need as well. I have coded up a solution but can't seem to be able to push my branch to create a pull request. Any help would be appreciated.

**Comment by PeterNgTr** [comment]
I think it can be closed cause the PR has been merged.
