### ISSUE TITLE
Override utcnow() to specific timezone

### ISSUE THREAD

**Issue by brianbautista** [allankp/pytest-testrail#96]
Not necessarily a bug but Is there a way to override the `datetime.utcnow()` in the `testrun_name` to a specific timezone?  

https://github.com/allankp/pytest-testrail/blob/92d0a279da0f12b912c3ad5c65561a3fb8c874a7/pytest_testrail/plugin.py#L89

**Comment by apallier** [comment]
Hi @brianbautista, what do you want to do ? Change the test run name ?

**Comment by brianbautista** [comment]
For example, the testruns are being named as `Automated Run 24-07-2019 00:26:25` automatically.  I would like to change the date format to `YYYY-MM-DD` and the time to be my current time zone, `Pacific Time Zone USA UTC-8`.

**Comment by apallier** [comment]
@brianbautista in this case, there is no way to do that. Feel free to submit a Pull Request allowing to configure it.
